# Generated by Django 3.2.15 on 2024-11-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('product_quantity', models.PositiveIntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
